# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lks.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(331, 240)
        self.radioButton1 = QtWidgets.QRadioButton(Form)
        self.radioButton1.setGeometry(QtCore.QRect(230, 30, 89, 16))
        self.radioButton1.setObjectName("radioButton1")
        self.radioButton_2 = QtWidgets.QRadioButton(Form)
        self.radioButton_2.setGeometry(QtCore.QRect(230, 60, 89, 16))
        self.radioButton_2.setObjectName("radioButton_2")
        self.label1 = QtWidgets.QLabel(Form)
        self.label1.setGeometry(QtCore.QRect(230, 120, 54, 12))
        self.label1.setObjectName("label1")
        self.lineEdit1 = QtWidgets.QLineEdit(Form)
        self.lineEdit1.setGeometry(QtCore.QRect(270, 110, 41, 31))
        self.lineEdit1.setObjectName("lineEdit1")




        self.textBrowser1 = QtWidgets.QTextBrowser(Form)
        self.textBrowser1.setGeometry(QtCore.QRect(10, 10, 181, 201))
        self.textBrowser1.setObjectName("textBrowser1")
        self.pushButton1 = QtWidgets.QPushButton(Form)
        self.pushButton1.setGeometry(QtCore.QRect(230, 190, 75, 23))
        self.pushButton1.setObjectName("pushButton1")
        self.label1.setBuddy(self.lineEdit1)

        self.retranslateUi(Form)
        self.pushButton1.clicked['bool'].connect(self.lineEdit1.copy)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.radioButton1.setText(_translate("Form", "今日头条"))
        self.radioButton_2.setText(_translate("Form", "新浪微博"))
        self.label1.setText(_translate("Form", "&Num："))
        self.pushButton1.setText(_translate("Form", "OK"))
